services:
  gpu-worker:
    image: mobile-o-api:latest
    container_name: mobile-o-gpu-worker
    volumes:
      - .:/workspaces/mobile-o-inference
    working_dir: /workspaces/mobile-o-inference
    entrypoint: []
    command: python gpu_worker.py --model_path checkpoints/final_merged_model_23620
    environment:
      - REDIS_ACCESS_KEY=${REDIS_ACCESS_KEY:-}
      - REDIS_HOST=${REDIS_HOST:-rpc.centralus.redis.azure.net}
      - REDIS_PORT=${REDIS_PORT:-10000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
